# **Exploratory Data Analysis**

**Import necessary packages**

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

**Import dataset from excel and show the 5 first rows**

In [65]:
df = pd.read_excel("gdpdata.xlsx", header=1)
df.head()

,Country Code,Country,Year,GDP_per_capita_growth,gini_mkt,gini_disp,gem1,ge0,ge1,ge2,...,Household Consumption,Government Expenditure,R & D,Consumption,Savings,Political Stability,Financial Development_2,Power Distributed by Socio-Economic Position,Government_Consumption,Redistribution
0,AFG,Afghanistan,1980,-0.391007,31.10,29.40,55.3516,45.985364,50.205709,81.180509,...,92.303347,41.696368,0.0,114.412567,-2.737769,-2.452497,2.857472,0.263158,22.109219,1.7
1,AFG,Afghanistan,1981,12.266928,31.18,29.48,55.2956,45.625818,49.746345,80.334145,...,92.303347,41.696368,0.0,114.412567,-2.737769,-2.452497,2.435703,0.263158,22.109219,1.7
2,AFG,Afghanistan,1982,11.013986,31.26,29.56,55.2396,45.266273,49.286982,79.487782,...,92.303347,37.025234,0.0,114.412567,-2.737769,-2.150598,4.851033,0.263158,22.109219,1.7
3,AFG,Afghanistan,1983,6.062992,31.34,29.64,55.1836,44.906727,48.827618,78.641418,...,92.303347,37.025234,0.0,114.412567,-2.737769,-2.150598,4.851033,0.263158,22.109219,1.7
4,AFG,Afghanistan,1984,-0.742390,31.42,29.72,55.1276,44.547182,48.368255,77.795055,...,92.303347,37.025234,0.0,114.412567,-2.737769,-2.150598,4.851033,0.263158,22.109219,1.7

**Getting the Shape of the DataFrame**

-The first integer is the number of rows in the DataFrame.

-The second integer is the number of columns in the DataFrame.

In [3]:
df.shape

(6150, 63)

**Getting DataFrame Information**

The output includes:
The number of entries (rows) in the DataFrame.

*   The number of columns and their names.
*   The non-null counts for each column, which helps identify missing values.
*   The data types of each column, which is useful for understanding
*   The kind of data stored in each column (e.g., integer, float, object/string).

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6150 entries, 0 to 6149
Data columns (total 63 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Country Code                                  6150 non-null   object
 1   Country                                       6150 non-null   object
 2   Year                                          6150 non-null   int64
 3   GDP_per_capita_growth                         6150 non-null   float64
 4   gini_mkt                                      6150 non-null   float64
 5   gini_disp                                     6150 non-null   float64
 6   gem1                                          6150 non-null   float64
 7   ge0                                           6150 non-null   float64
 8   ge1                                           6150 non-null   float64
 9   ge2                                           6150 non-null   float64
 10  a025                                          6150 non-null   float64
 11  a050                                          6150 non-null   float64
 12  a075                                          6150 non-null   float64
 13  a1                                            6150 non-null   float64
 14  a2                                            6150 non-null   float64
 15  palma                                         6150 non-null   float64
 16  s80s20                                        6150 non-null   float64
 17  bottom5                                       6150 non-null   float64
 18  bottom20                                      6150 non-null   float64
 19  bottom40                                      6150 non-null   float64
 20  top5                                          6150 non-null   float64
 21  top10                                         6150 non-null   float64
 22  top20                                         6150 non-null   float64
 23  middle50                                      6150 non-null   float64
 24  ginia                                         6150 non-null   float64
 25  sd                                            6150 non-null   float64
 26  Povertygapat$1.90                             6150 non-null   float64
 27  Poverty gap at $3.20                          6150 non-null   float64
 28  Poverty gap at $5.50                          6150 non-null   float64
 29  Poverty headcount ratio at $1.90              6150 non-null   float64
 30  Poverty headcount ratio at $3.20              6150 non-null   float64
 31  Poverty headcount ratio at $5.50              6150 non-null   float64
 32  Wealth Gini                                   6150 non-null   float64
 33  Wealth top 1%                                 6150 non-null   float64
 34  Wealth top 10%                                6150 non-null   float64
 35  Wealth middle 40%                             6150 non-null   float64
 36  Wealth bottom 50%                             6150 non-null   float64
 37  GDP per capita                                6150 non-null   float64
 38  Avg. years of Education                       6150 non-null   float64
 39  Trade_Openness                                6150 non-null   float64
 40  Investment                                    6150 non-null   float64
 41  FDI                                           6150 non-null   float64
 42  Working age population %                      6150 non-null   float64
 43  Patent Stock                                  6150 non-null   int64
 44  Financial Development                         6150 non-null   float64
 45  Infrastructure Development                    6150 non-null   float64
 46  inflation                                     6150 non-null   float64
 47  Corruption                                    6150 non-null   float64
 48  Price Level of Investment                     6150 non-null   float64
 49  Government Effectiveness                      6150 non-null   float64
 50  Country/Code                                  6150 non-null   int64
 51  Cluster                                       6150 non-null   int64
 52  Tax                                           6109 non-null   float64
 53  Household Consumption                         6150 non-null   float64
 54  Government Expenditure                        6150 non-null   float64
 55  R & D                                         6150 non-null   float64
 56  Consumption                                   6150 non-null   float64
 57  Savings                                       6150 non-null   float64
 58  Political Stability                           6150 non-null   float64
 59  Financial Development_2                       6150 non-null   float64
 60  Power Distributed by Socio-Economic Position  6109 non-null   float64
 61  Government_Consumption                        6150 non-null   float64
 62  Redistribution                                6150 non-null   float64
dtypes: float64(57), int64(4), object(2)
memory usage: 3.0+ MB

**Accessing Column Names**

In [5]:
df.columns

Index(['Country Code', 'Country', 'Year', 'GDP_per_capita_growth', 'gini_mkt',
       'gini_disp', 'gem1', 'ge0', 'ge1', 'ge2', 'a025', 'a050', 'a075', 'a1',
       'a2', 'palma', 's80s20', 'bottom5', 'bottom20', 'bottom40', 'top5',
       'top10', 'top20', 'middle50', 'ginia', 'sd', 'Povertygapat$1.90',
       'Poverty gap at $3.20 ', 'Poverty gap at $5.50 ',
       'Poverty headcount ratio at $1.90 ',
       'Poverty headcount ratio at $3.20 ',
       'Poverty headcount ratio at $5.50 ', 'Wealth Gini', 'Wealth top 1% ',
       'Wealth top 10%', 'Wealth middle 40%', 'Wealth bottom 50%',
       'GDP per capita', 'Avg. years of Education', 'Trade_Openness',
       'Investment', 'FDI', 'Working age population %', 'Patent Stock',
       'Financial Development', 'Infrastructure Development', 'inflation',
       'Corruption', 'Price Level of Investment', 'Government Effectiveness',
       'Country/Code', 'Cluster', 'Tax', 'Household Consumption',
       'Government Expenditure', 'R & D', 'Consumption', 'Savings',
       'Political Stability', 'Financial Development_2',
       'Power Distributed by Socio-Economic Position',
       'Government_Consumption', 'Redistribution'],
      dtype='object')

**Changing the Data Type of a Column**

In [67]:
df["Cluster"] = df["Cluster"].astype("object")

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6150 entries, 0 to 6149
Data columns (total 63 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Country Code                                  6150 non-null   object
 1   Country                                       6150 non-null   object
 2   Year                                          6150 non-null   int64
 3   GDP_per_capita_growth                         6150 non-null   float64
 4   gini_mkt                                      6150 non-null   float64
 5   gini_disp                                     6150 non-null   float64
 6   gem1                                          6150 non-null   float64
 7   ge0                                           6150 non-null   float64
 8   ge1                                           6150 non-null   float64
 9   ge2                                           6150 non-null   float64
 10  a025                                          6150 non-null   float64
 11  a050                                          6150 non-null   float64
 12  a075                                          6150 non-null   float64
 13  a1                                            6150 non-null   float64
 14  a2                                            6150 non-null   float64
 15  palma                                         6150 non-null   float64
 16  s80s20                                        6150 non-null   float64
 17  bottom5                                       6150 non-null   float64
 18  bottom20                                      6150 non-null   float64
 19  bottom40                                      6150 non-null   float64
 20  top5                                          6150 non-null   float64
 21  top10                                         6150 non-null   float64
 22  top20                                         6150 non-null   float64
 23  middle50                                      6150 non-null   float64
 24  ginia                                         6150 non-null   float64
 25  sd                                            6150 non-null   float64
 26  Povertygapat$1.90                             6150 non-null   float64
 27  Poverty gap at $3.20                          6150 non-null   float64
 28  Poverty gap at $5.50                          6150 non-null   float64
 29  Poverty headcount ratio at $1.90              6150 non-null   float64
 30  Poverty headcount ratio at $3.20              6150 non-null   float64
 31  Poverty headcount ratio at $5.50              6150 non-null   float64
 32  Wealth Gini                                   6150 non-null   float64
 33  Wealth top 1%                                 6150 non-null   float64
 34  Wealth top 10%                                6150 non-null   float64
 35  Wealth middle 40%                             6150 non-null   float64
 36  Wealth bottom 50%                             6150 non-null   float64
 37  GDP per capita                                6150 non-null   float64
 38  Avg. years of Education                       6150 non-null   float64
 39  Trade_Openness                                6150 non-null   float64
 40  Investment                                    6150 non-null   float64
 41  FDI                                           6150 non-null   float64
 42  Working age population %                      6150 non-null   float64
 43  Patent Stock                                  6150 non-null   int64
 44  Financial Development                         6150 non-null   float64
 45  Infrastructure Development                    6150 non-null   float64
 46  inflation                                     6150 non-null   float64
 47  Corruption                                    6150 non-null   float64
 48  Price Level of Investment                     6150 non-null   float64
 49  Government Effectiveness                      6150 non-null   float64
 50  Country/Code                                  6150 non-null   int64
 51  Cluster                                       6150 non-null   object
 52  Tax                                           6109 non-null   float64
 53  Household Consumption                         6150 non-null   float64
 54  Government Expenditure                        6150 non-null   float64
 55  R & D                                         6150 non-null   float64
 56  Consumption                                   6150 non-null   float64
 57  Savings                                       6150 non-null   float64
 58  Political Stability                           6150 non-null   float64
 59  Financial Development_2                       6150 non-null   float64
 60  Power Distributed by Socio-Economic Position  6109 non-null   float64
 61  Government_Consumption                        6150 non-null   float64
 62  Redistribution                                6150 non-null   float64
dtypes: float64(57), int64(3), object(3)
memory usage: 3.0+ MB

**Descriptive Statistics for Specific Data Types**

In [68]:
df.describe(include=["object", "bool"])

       Country Code      Country  Cluster
count          6150         6150     6150
unique          150          150        4
top             AFG  Afghanistan        2
freq             41           41     2296

**Counting Unique Values in a Column**

In [9]:
df["Cluster"].value_counts()

Cluster
2    2296
3    1886
1    1271
4     697
Name: count, dtype: int64

**Counting and Normalizing Unique Values in a Column**

It helps to see what percentage of the data belongs to each category or group.

In [10]:
df["Cluster"].value_counts(normalize=True)

Cluster
2    0.373333
3    0.306667
1    0.206667
4    0.113333
Name: proportion, dtype: float64

In [11]:
df["Country"].value_counts()

Country
Afghanistan      41
Montenegro       41
Mozambique       41
Mauritania       41
Mauritius        41
                 ..
Ghana            41
Guinea           41
Gambia, The      41
Guinea-Bissau    41
Zimbabwe         41
Name: count, Length: 150, dtype: int64

**Calculating the Mean of a Column**

In [69]:
df["inflation"].mean()

56.699299833470675

In [13]:
df.head ()

,Country Code,Country,Year,GDP_per_capita_growth,gini_mkt,gini_disp,gem1,ge0,ge1,ge2,...,Household Consumption,Government Expenditure,R & D,Consumption,Savings,Political Stability,Financial Development_2,Power Distributed by Socio-Economic Position,Government_Consumption,Redistribution
0,AFG,Afghanistan,1980,-0.391007,31.10,29.40,55.3516,45.985364,50.205709,81.180509,...,92.303347,41.696368,0.0,114.412567,-2.737769,-2.452497,2.857472,0.263158,22.109219,1.7
1,AFG,Afghanistan,1981,12.266928,31.18,29.48,55.2956,45.625818,49.746345,80.334145,...,92.303347,41.696368,0.0,114.412567,-2.737769,-2.452497,2.435703,0.263158,22.109219,1.7
2,AFG,Afghanistan,1982,11.013986,31.26,29.56,55.2396,45.266273,49.286982,79.487782,...,92.303347,37.025234,0.0,114.412567,-2.737769,-2.150598,4.851033,0.263158,22.109219,1.7
3,AFG,Afghanistan,1983,6.062992,31.34,29.64,55.1836,44.906727,48.827618,78.641418,...,92.303347,37.025234,0.0,114.412567,-2.737769,-2.150598,4.851033,0.263158,22.109219,1.7
4,AFG,Afghanistan,1984,-0.742390,31.42,29.72,55.1276,44.547182,48.368255,77.795055,...,92.303347,37.025234,0.0,114.412567,-2.737769,-2.150598,4.851033,0.263158,22.109219,1.7

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6150 entries, 0 to 6149
Data columns (total 63 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Country Code                                  6150 non-null   object
 1   Country                                       6150 non-null   object
 2   Year                                          6150 non-null   int64
 3   GDP_per_capita_growth                         6150 non-null   float64
 4   gini_mkt                                      6150 non-null   float64
 5   gini_disp                                     6150 non-null   float64
 6   gem1                                          6150 non-null   float64
 7   ge0                                           6150 non-null   float64
 8   ge1                                           6150 non-null   float64
 9   ge2                                           6150 non-null   float64
 10  a025                                          6150 non-null   float64
 11  a050                                          6150 non-null   float64
 12  a075                                          6150 non-null   float64
 13  a1                                            6150 non-null   float64
 14  a2                                            6150 non-null   float64
 15  palma                                         6150 non-null   float64
 16  s80s20                                        6150 non-null   float64
 17  bottom5                                       6150 non-null   float64
 18  bottom20                                      6150 non-null   float64
 19  bottom40                                      6150 non-null   float64
 20  top5                                          6150 non-null   float64
 21  top10                                         6150 non-null   float64
 22  top20                                         6150 non-null   float64
 23  middle50                                      6150 non-null   float64
 24  ginia                                         6150 non-null   float64
 25  sd                                            6150 non-null   float64
 26  Povertygapat$1.90                             6150 non-null   float64
 27  Poverty gap at $3.20                          6150 non-null   float64
 28  Poverty gap at $5.50                          6150 non-null   float64
 29  Poverty headcount ratio at $1.90              6150 non-null   float64
 30  Poverty headcount ratio at $3.20              6150 non-null   float64
 31  Poverty headcount ratio at $5.50              6150 non-null   float64
 32  Wealth Gini                                   6150 non-null   float64
 33  Wealth top 1%                                 6150 non-null   float64
 34  Wealth top 10%                                6150 non-null   float64
 35  Wealth middle 40%                             6150 non-null   float64
 36  Wealth bottom 50%                             6150 non-null   float64
 37  GDP per capita                                6150 non-null   float64
 38  Avg. years of Education                       6150 non-null   float64
 39  Trade_Openness                                6150 non-null   float64
 40  Investment                                    6150 non-null   float64
 41  FDI                                           6150 non-null   float64
 42  Working age population %                      6150 non-null   float64
 43  Patent Stock                                  6150 non-null   int64
 44  Financial Development                         6150 non-null   float64
 45  Infrastructure Development                    6150 non-null   float64
 46  inflation                                     6150 non-null   float64
 47  Corruption                                    6150 non-null   float64
 48  Price Level of Investment                     6150 non-null   float64
 49  Government Effectiveness                      6150 non-null   float64
 50  Country/Code                                  6150 non-null   int64
 51  Cluster                                       6150 non-null   object
 52  Tax                                           6109 non-null   float64
 53  Household Consumption                         6150 non-null   float64
 54  Government Expenditure                        6150 non-null   float64
 55  R & D                                         6150 non-null   float64
 56  Consumption                                   6150 non-null   float64
 57  Savings                                       6150 non-null   float64
 58  Political Stability                           6150 non-null   float64
 59  Financial Development_2                       6150 non-null   float64
 60  Power Distributed by Socio-Economic Position  6109 non-null   float64
 61  Government_Consumption                        6150 non-null   float64
 62  Redistribution                                6150 non-null   float64
dtypes: float64(57), int64(3), object(3)
memory usage: 3.0+ MB

In [15]:
df.columns

Index(['Country Code', 'Country', 'Year', 'GDP_per_capita_growth', 'gini_mkt',
       'gini_disp', 'gem1', 'ge0', 'ge1', 'ge2', 'a025', 'a050', 'a075', 'a1',
       'a2', 'palma', 's80s20', 'bottom5', 'bottom20', 'bottom40', 'top5',
       'top10', 'top20', 'middle50', 'ginia', 'sd', 'Povertygapat$1.90',
       'Poverty gap at $3.20 ', 'Poverty gap at $5.50 ',
       'Poverty headcount ratio at $1.90 ',
       'Poverty headcount ratio at $3.20 ',
       'Poverty headcount ratio at $5.50 ', 'Wealth Gini', 'Wealth top 1% ',
       'Wealth top 10%', 'Wealth middle 40%', 'Wealth bottom 50%',
       'GDP per capita', 'Avg. years of Education', 'Trade_Openness',
       'Investment', 'FDI', 'Working age population %', 'Patent Stock',
       'Financial Development', 'Infrastructure Development', 'inflation',
       'Corruption', 'Price Level of Investment', 'Government Effectiveness',
       'Country/Code', 'Cluster', 'Tax', 'Household Consumption',
       'Government Expenditure', 'R & D', 'Consumption', 'Savings',
       'Political Stability', 'Financial Development_2',
       'Power Distributed by Socio-Economic Position',
       'Government_Consumption', 'Redistribution'],
      dtype='object')

**Dropping Columns from a DataFrame**

This is useful when you want to focus on specific features and exclude those that may not be relevant to your analysis or that could introduce noise

In [70]:
dfnew = df.drop(["Country", "Cluster", 'Country Code'], axis=1)

**Applying a Function (Median) Across DataFrame Columns**

In [71]:
dfnew.apply(np.median)

Year                                            2000.000000
GDP_per_capita_growth                              1.930429
gini_mkt                                          44.700000
gini_disp                                         38.500000
gem1                                              43.895345
ge0                                               31.374000
ge1                                               32.290500
ge2                                               45.909000
a025                                               7.660000
a050                                              14.622000
a075                                              21.107500
a1                                                26.956500
a2                                                47.301000
palma                                              2.099482
s80s20                                             7.325500
bottom5                                            0.688000
bottom20                                           5.290227
bottom40                                          15.295500
top5                                              21.327500
top10                                             32.413409
top20                                             39.457500
middle50                                          51.733409
ginia                                            360.370014
sd                                                81.842648
Povertygapat$1.90                                  1.600000
Poverty gap at $3.20                               6.117143
Poverty gap at $5.50                              18.529394
Poverty headcount ratio at $1.90                   5.700000
Poverty headcount ratio at $3.20                  20.008182
Poverty headcount ratio at $5.50                  47.863636
Wealth Gini                                        0.744972
Wealth top 1%                                      0.271509
Wealth top 10%                                     0.603500
Wealth middle 40%                                  0.346700
Wealth bottom 50%                                  0.048400
GDP per capita                                  2215.145781
Avg. years of Education                            7.383250
Trade_Openness                                    67.408241
Investment                                        22.110104
FDI                                                1.933033
Working age population %                          61.829302
Patent Stock                                      36.000000
Financial Development                             28.232565
Infrastructure Development                        14.621279
inflation                                          5.949669
Corruption                                         0.468890
Price Level of Investment                          0.455605
Government Effectiveness                          -0.215992
Country/Code                                      74.500000
Tax                                                     NaN
Household Consumption                             63.026820
Government Expenditure                            20.342858
R & D                                              0.285549
Consumption                                       79.182088
Savings                                           19.983435
Political Stability                               -0.166409
Financial Development_2                           29.009670
Power Distributed by Socio-Economic Position            NaN
Government_Consumption                            15.226265
Redistribution                                     2.620000
dtype: float64

**Calculating the Mode of a Column**

In [72]:
dfnew ["Savings"].mode()

0    0.0
Name: Savings, dtype: float64

**Grouping Data and Calculating Mean**

It calculates the average of a specified column within each subgroup defined by another column, allowing for comparison of the average values across different groups.

In [73]:
df.groupby("Cluster")["Tax"].mean()

Cluster
1    20.045526
2    11.228100
3    11.034427
4    15.822427
Name: Tax, dtype: float64

In addition to grouping , it sorts these averages from highest to lowest.

In [20]:
df.groupby("Country")["gini_mkt"].mean().sort_values(ascending=False)

Country
Namibia                     69.020732
Botswana                    61.430488
Brazil                      60.390488
Haiti                       57.207561
Central African Republic    57.032683
                              ...
Myanmar                     34.883415
Korea, Republic of          34.392195
Afghanistan                 32.720732
Belarus                     31.995366
Ukraine                     23.429268
Name: gini_mkt, Length: 150, dtype: float64

**Creating a Cross-Tabulation Table**

It generates a table that counts the occurrences of each combination of values from two categorical variables, allowing for easy comparison and analysis of their relationships.

In [74]:
pd.crosstab(df["Cluster"], df["Country"])

Country,Afghanistan,Albania,Algeria,Angola,Argentina,Armenia,Australia,Austria,Azerbaijan,Bahrain,...,Ukraine,United Kingdom,United States,Uruguay,Uzbekistan,Venezuela,Vietnam,Yemen,Zambia,Zimbabwe
Cluster,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,41,41,0,0,...,0,41,41,0,0,0,0,0,0,0
2,0,41,41,0,41,41,0,0,0,41,...,0,0,0,41,41,41,41,41,0,0
3,41,0,0,41,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,41,41
4,0,0,0,0,0,0,0,0,41,0,...,41,0,0,0,0,0,0,0,0,0

**Creating a Pivot Table**

It creates a summary table that aggregates data based on specified rows and values, allowing for easy analysis and comparison of data.

In [22]:
df.pivot_table(index="Cluster", values="Tax")

               Tax
Cluster
1        20.045526
2        11.228100
3        11.034427
4        15.822427

**Retrieving Column Names**

In [75]:
df.columns

Index(['Country Code', 'Country', 'Year', 'GDP_per_capita_growth', 'gini_mkt',
       'gini_disp', 'gem1', 'ge0', 'ge1', 'ge2', 'a025', 'a050', 'a075', 'a1',
       'a2', 'palma', 's80s20', 'bottom5', 'bottom20', 'bottom40', 'top5',
       'top10', 'top20', 'middle50', 'ginia', 'sd', 'Povertygapat$1.90',
       'Poverty gap at $3.20 ', 'Poverty gap at $5.50 ',
       'Poverty headcount ratio at $1.90 ',
       'Poverty headcount ratio at $3.20 ',
       'Poverty headcount ratio at $5.50 ', 'Wealth Gini', 'Wealth top 1% ',
       'Wealth top 10%', 'Wealth middle 40%', 'Wealth bottom 50%',
       'GDP per capita', 'Avg. years of Education', 'Trade_Openness',
       'Investment', 'FDI', 'Working age population %', 'Patent Stock',
       'Financial Development', 'Infrastructure Development', 'inflation',
       'Corruption', 'Price Level of Investment', 'Government Effectiveness',
       'Country/Code', 'Cluster', 'Tax', 'Household Consumption',
       'Government Expenditure', 'R & D', 'Consumption', 'Savings',
       'Political Stability', 'Financial Development_2',
       'Power Distributed by Socio-Economic Position',
       'Government_Consumption', 'Redistribution'],
      dtype='object')

**Creating a Pivot Table with Multiple Values**

It generates a pivot table that calculates the average of multiple columns for each category defined by another column

In [76]:
df.pivot_table(
    ["Tax", "palma", "FDI"],["Cluster"],
    aggfunc="mean",
)

              FDI        Tax     palma
Cluster
1        6.546277  20.045526  1.191760
2        2.956836  11.228100  2.359135
3        2.681721  11.034427  5.858403
4        4.165367  15.822427  1.250837

**Calculating and Sorting Missing Values**

It calculates the number of missing values in each column and sorts the columns based on the number of missing values, from highest to lowest.

In [78]:
total = df.isnull().sum().sort_values(ascending=False)

**Generating Descriptive Statistics for numerical variables**

It generates and prints a summary of descriptive statistics for numerical columns in the DataFrame, including measures like mean, standard deviation, and percentiles.

In [79]:
summary_stats = dfnew.describe()
print(summary_stats)

              Year  GDP_per_capita_growth     gini_mkt    gini_disp  \
count  6150.000000            6150.000000  6150.000000  6150.000000
mean   2000.000000               1.480445    44.844431    38.408403
std      11.833122               6.464834     6.428797     8.557746
min    1980.000000             -64.992369    21.760000    14.240000
25%    1990.000000              -0.618335    40.500000    32.200000
50%    2000.000000               1.930429    44.700000    38.500000
75%    2010.000000               4.105697    48.800000    44.000000
max    2020.000000             105.439058    69.890000    66.810000

              gem1          ge0          ge1          ge2         a025  \
count  6150.000000  6150.000000  6150.000000  6150.000000  6150.000000
mean     87.339622    38.406252    38.904626    69.308649     9.060161
std     154.948495    26.224648    25.188760    67.525667     5.536696
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%      24.076750    20.056750    19.955159    24.359250     4.881250
50%      43.895345    31.374000    32.290500    45.909000     7.660000
75%      88.375000    52.049500    55.193000   100.578636    12.690250
max    2081.154255   209.902127   177.336164   662.514964    36.870164

              a050  ...  Household Consumption  Government Expenditure  \
count  6150.000000  ...            6150.000000             6150.000000
mean     16.932777  ...              61.558110               21.533650
std       9.752494  ...              20.601298               13.697545
min       0.000000  ...               0.000000                0.000000
25%       9.582750  ...              52.872262               13.102823
50%      14.622000  ...              63.026820               20.342858
75%      23.438864  ...              74.503928               30.774613
max      63.809400  ...             165.503835              210.205132

             R & D  Consumption      Savings  Political Stability  \
count  6150.000000  6150.000000  6150.000000          6150.000000
mean      0.599613    76.649762    19.022715            -0.198384
std       0.816594    22.150754    14.702893             0.954924
min       0.000000     0.000000  -236.242262            -3.180352
25%       0.064742    70.784313    12.950635            -0.852054
50%       0.285549    79.182088    19.983435            -0.166409
75%       0.704085    88.782448    26.611797             0.559495
max       5.705550   186.912124    71.297498             1.758681

       Financial Development_2  Power Distributed by Socio-Economic Position  \
count              6150.000000                                   6109.000000
mean                 42.263171                                      0.491756
std                  39.252168                                      0.290430
min                   0.000000                                      0.000000
25%                  13.271313                                      0.236842
50%                  29.009670                                      0.473684
75%                  58.877583                                      0.736842
max                 304.574500                                      1.000000

       Government_Consumption  Redistribution
count             6150.000000     6150.000000
mean                15.026971        6.436028
std                  6.454674        7.062133
min                  0.000000       -9.840000
25%                 10.974690        1.900000
50%                 15.226265        2.620000
75%                 19.207009       11.500000
max                 76.222125       25.800000

[8 rows x 60 columns]

**Calculating Skewness and Kurtosis**

It calculates and prints the skewness and kurtosis for each numerical column in the DataFrame, providing insights into the distribution shape and data variability.

In [36]:
skew_kurt = dfnew.agg(['skew', 'kurtosis'])
print(skew_kurt)

             Year  GDP_per_capita_growth  gini_mkt  gini_disp       gem1  \
skew      0.00000               1.056320  0.209599   0.107779   5.945913
kurtosis -1.20143              36.664257  1.358881  -0.160966  47.031013

               ge0       ge1        ge2      a025      a050  ...  \
skew      1.909605  1.358734   2.815592  1.224216  1.096860  ...
kurtosis  6.000869  2.908033  13.246450  2.265657  1.732424  ...

          Household Consumption  Government Expenditure     R & D  \
skew                  -0.971302                0.836634  2.044042
kurtosis               2.023547                6.634024  4.014194

          Consumption    Savings  Political Stability  \
skew        -1.730813  -3.216010            -0.293301
kurtosis     4.624868  31.556429            -0.492978

          Financial Development_2  \
skew                     1.559036
kurtosis                 2.546428

          Power Distributed by Socio-Economic Position  \
skew                                          0.028947
kurtosis                                     -1.153300

          Government_Consumption  Redistribution
skew                    0.120116        0.844233
kurtosis                2.156686       -0.364238

[2 rows x 60 columns]

**Displaying Data Types of Columns**

In [48]:
print(df.dtypes)

Country Code                                     object
Country                                          object
Year                                              int64
GDP_per_capita_growth                           float64
gini_mkt                                        float64
                                                 ...
Political Stability                             float64
Financial Development_2                         float64
Power Distributed by Socio-Economic Position    float64
Government_Consumption                          float64
Redistribution                                  float64
Length: 63, dtype: object

**Selecting Numerical Columns**

It selects columns with numerical data types from the DataFrame and displays the first 5 rows of the resulting DataFrame

In [56]:
df_num = df.select_dtypes(include = ['float64', 'int64'])
df_num.head()

,Year,GDP_per_capita_growth,gini_mkt,gini_disp,gem1,ge0,ge1,ge2,a025,a050,...,Household Consumption,Government Expenditure,R & D,Consumption,Savings,Political Stability,Financial Development_2,Power Distributed by Socio-Economic Position,Government_Consumption,Redistribution
0,1980,-0.391007,31.10,29.40,55.3516,45.985364,50.205709,81.180509,11.709436,21.766145,...,92.303347,41.696368,0.0,114.412567,-2.737769,-2.452497,2.857472,0.263158,22.109219,1.7
1,1981,12.266928,31.18,29.48,55.2956,45.625818,49.746345,80.334145,11.605982,21.584327,...,92.303347,41.696368,0.0,114.412567,-2.737769,-2.452497,2.435703,0.263158,22.109219,1.7
2,1982,11.013986,31.26,29.56,55.2396,45.266273,49.286982,79.487782,11.502527,21.402509,...,92.303347,37.025234,0.0,114.412567,-2.737769,-2.150598,4.851033,0.263158,22.109219,1.7
3,1983,6.062992,31.34,29.64,55.1836,44.906727,48.827618,78.641418,11.399073,21.220691,...,92.303347,37.025234,0.0,114.412567,-2.737769,-2.150598,4.851033,0.263158,22.109219,1.7
4,1984,-0.742390,31.42,29.72,55.1276,44.547182,48.368255,77.795055,11.295618,21.038873,...,92.303347,37.025234,0.0,114.412567,-2.737769,-2.150598,4.851033,0.263158,22.109219,1.7

**Listing Unique Data Types**

It creates a list of unique data types present in the DataFrame, providing an overview of the different types of data stored in the columns.

In [80]:
list(set(df.dtypes.tolist()))

[dtype('float64'), dtype('O'), dtype('int64')]

**Identifying Strong Correlations with a Target Variable**

It identifies and displays features that have a strong correlation with a target variable, showing those with significant relationships.

In [84]:
df_num_corr = df_num.corr()['Savings'][:-1]
golden_features_list = df_num_corr[abs(df_num_corr) > 0.5].sort_values(ascending=False)
print("There is {} strongly correlated values with Savings:\n{}".format(len(golden_features_list), golden_features_list))

There is 1 strongly correlated values with Savings:
Savings    1.0
Name: Savings, dtype: float64